# replace "qudo" with project name
name: qudo-shared
networks:
  qudo-network:
    driver: bridge
volumes:
  qudo-volume:
services:
  qudo-redis:
    networks:
      - qudo-network
    container_name: qudo-redis
    image: redis
    ports:
      - "6379:6379"
  qudo-upstash:
    networks:
      - qudo-network
    container_name: qudo-redis-upstash
    ports:
      - "8002:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      # Using `redis` hostname:port since they're in the same Docker network.
      SRH_CONNECTION_STRING: "redis://redis:6379"
  qudo-database:
    image: postgres:latest
    container_name: qudo-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=qudo
    ports:
      - "5436:5432"
    command: -c listen_addresses=0.0.0.0
    restart: unless-stopped
    networks:
      - qudo-network
    volumes:
      - qudo-volume:/var/lib/postgresql/data
